import './styles.css';
import { logoUrl, setLogoOverrides } from './logos.js';
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderInteractivePie(items,total,palette){
  const box=document.querySelector('.pie-chart');if(!box)return;
  const ns='http://www.w3.org/2000/svg',cx=50,cy=50,outer=47,inner=20;let angle=-90;
  const point=(radius,degrees)=>{const radians=degrees*Math.PI/180;return [cx+radius*Math.cos(radians),cy+radius*Math.sin(radians)]};
  const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 100 100');svg.setAttribute('role','img');svg.setAttribute('aria-label','กราฟสัดส่วนข้อมูล');
  items.forEach(([name,count],index)=>{const start=angle,end=angle+count/total*360;angle=end;const p1=point(outer,start),p2=point(outer,end),p3=point(inner,end),p4=point(inner,start),large=end-start>180?'1':'0';const path=document.createElementNS(ns,'path');path.setAttribute('d','M '+p1.join(' ')+' A '+outer+' '+outer+' 0 '+large+' 1 '+p2.join(' ')+' L '+p3.join(' ')+' A '+inner+' '+inner+' 0 '+large+' 0 '+p4.join(' ')+' Z');path.setAttribute('fill',palette[index%palette.length]);path.dataset.index=index;path.classList.add('pie-slice');path.setAttribute('tabindex','0');path.setAttribute('aria-label',name+' '+count+' รายการ');svg.appendChild(path)});
  box.classList.add('has-svg');box.innerHTML='';box.appendChild(svg);const center=document.createElement('span');center.innerHTML=String(total)+'<small>รายการ</small>';box.appendChild(center);
  const select=index=>{box.querySelectorAll('.pie-slice').forEach((slice,i)=>{slice.classList.toggle('is-active',i===index);slice.classList.toggle('is-dimmed',index!==null&&i!==index)});document.querySelectorAll('.pie-legend-row').forEach((row,i)=>{row.classList.toggle('is-active',i===index);row.classList.toggle('is-dimmed',index!==null&&i!==index)})};
  box.querySelectorAll('.pie-slice').forEach(slice=>{slice.onclick=()=>select(Number(slice.dataset.index));slice.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(Number(slice.dataset.index))}}});document.querySelectorAll('.pie-legend-row').forEach((row,i)=>{row.style.cursor='pointer';row.onclick=()=>select(i)});
}
document.querySelector('#app').innerHTML='<main class="loading-shell"><div class="loading-orbit"></div><h1>กำลังเตรียมข้อมูลสถิติ</h1><p>กำลังโหลดและจัดเรียงข้อมูลการศึกษาต่อ...</p></main>';
let records=[], albums={}, years=[], selected='all', chartMode='institution';
fetch('./data_sources.json').then(r=>r.ok?r.json():{}).catch(()=>({})).then(sources=>{const base=sources.baseUrl||'';const get=(key,fallback)=>{const configured=import.meta.env.DEV?fallback:base+(sources[key]||fallback);const urls=[configured,fallback].filter((url,index,list)=>url&&!list.slice(0,index).includes(url));return urls.reduce((promise,url)=>promise.then(value=>value??fetch(url).then(r=>r.ok?r.json():null).catch(()=>null)),Promise.resolve(null)).then(value=>value||{})};return Promise.all([get('imageMetadata','./image_metadata.json'),get('albumSources','./album_sources.json'),get('institutionLogos','./institution_logos.json')])}).then(([data,albumData,logos])=>{
  records=Array.isArray(data)?data.filter(r=>r&&typeof r==='object'):[];
  albums=albumData&&typeof albumData==='object'?albumData:{};
  years=[...new Set(records.map(r=>r.year).filter(Boolean))].sort((a,b)=>b-a);
  setLogoOverrides(logos&&typeof logos==='object'?logos:{}); render();
}).catch(e=>document.querySelector('#app').innerHTML=`<p class="p-8 text-red-700">โหลดสถิติไม่สำเร็จ: ${esc(e.message)}</p>`);
function render(){
  const filtered=selected==='all'?records:records.filter(r=>String(r.year)===String(selected));
  const counts=new Map(); filtered.forEach(r=>{if(r.institution&&r.institution!=='ไม่ระบุจากภาพ')counts.set(r.institution,(counts.get(r.institution)||0)+1)});
  const ranking=[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'th')); const total=ranking.reduce((n,[,c])=>n+c,0); const max=ranking[0]?.[1]||1;
  document.querySelector('#app').innerHTML=`<main class="min-h-screen bg-[#f7f8fc]"><header class="site-hero"><div class="hero-inner"><a href="/" class="back-link">← กลับหน้ารูปภาพ</a><h1>สถิติการสอบติด</h1><p>เลือกดูแยกปี หรือรวมข้อมูลทุกปี</p></div></header><section class="stats-wrap"><div class="stats-filter"><label for="stats-year">ช่วงข้อมูล</label><select id="stats-year"><option value="all" ${selected==='all'?'selected':''}>รวมทุกปี</option>${years.map(y=>`<option value="${y}" ${String(selected)===String(y)?'selected':''}>ปี ${y}</option>`).join('')}</select>${selected!=='all'?`<a href="${esc(albums[selected]||'#')}" target="_blank" rel="noreferrer">เปิดอัลบั้มปี ${selected}</a>`:''}</div><div class="year-stats">${(selected==='all'?years:[''+selected]).map(y=>{const n=records.filter(r=>String(r.year)===String(y)).length;return `<div class="year-stat"><span>ปี ${y}</span><strong>${n}</strong><small>${records.length?((n/records.length)*100).toFixed(1):0}% ของข้อมูลทั้งหมด</small></div>`}).join('')}</div><section class="ranking-panel"><div class="ranking-title"><div><h2>${selected==='all'?'รวมทุกปี':`ปี ${selected}`}: มหาวิทยาลัย/สถาบัน</h2><p>โลโก้หน้าชื่อ · เปอร์เซ็นต์คิดจากรายการของช่วงที่เลือก</p></div><b>${total} รายการ</b></div><div class="ranking-list">${ranking.length?ranking.map(([name,count])=>{const pct=total?count/total*100:0;return `<div class="rank-row"><img class="rank-logo" src="${logoUrl(name)}" alt="" loading="lazy"><div class="rank-main"><div class="rank-label"><span>${esc(name)}</span><strong>${count} คน · ${pct.toFixed(1)}%</strong></div><div class="rank-track"><i style="width:${count/max*100}%"></i></div></div></div>`}).join(''):'<p class="text-slate-500">ยังไม่มีข้อมูลสำหรับช่วงนี้</p>'}</div></section></section></main>`;
  const typeCounts=new Map();filtered.forEach(r=>{const type=r.institutionType||'ไม่ระบุ';typeCounts.set(type,(typeCounts.get(type)||0)+1)});
  const typeTotal=[...typeCounts.values()].reduce((a,b)=>a+b,0)||1;
  const typeCards=[...typeCounts].sort((a,b)=>b[1]-a[1]).map(([type,count])=>`<div class="insight-type"><span>${esc(type)}</span><b>${count}</b><small>${(count/typeTotal*100).toFixed(1)}%</small></div>`).join('');
  const trend=years.map(year=>{const count=records.filter(r=>Number(r.year)===Number(year)).length;return `<div class="trend-item"><span>ปี ${year}</span><i><b style="width:${Math.max(5,count/(Math.max(...years.map(y=>records.filter(r=>Number(r.year)===Number(y)).length))||1)*100)}%"></b></i><strong>${count}</strong></div>`}).join('');
  const chartCounts=new Map();filtered.forEach(r=>{const value=chartMode==='faculty'?r.faculty:r.institution;if(value&&value!=='ไม่ระบุจากภาพ')chartCounts.set(value,(chartCounts.get(value)||0)+1)});
  const chartSorted=[...chartCounts].sort((a,b)=>b[1]-a[1]); const chartTop=chartSorted.slice(0,8); const chartOther=chartSorted.slice(8).reduce((n,[,c])=>n+c,0); if(chartOther)chartTop.push(['อื่น ๆ',chartOther]); const chartTotal=chartTop.reduce((n,[,c])=>n+c,0)||1; const palette=['#3730a3','#2563eb','#0891b2','#0d9488','#16a34a','#ca8a04','#ea580c','#db2777','#64748b']; let angle=0; const stops=chartTop.map(([name,count],i)=>{const start=angle;angle+=count/chartTotal*360;return `${palette[i%palette.length]} ${start}deg ${angle}deg`}).join(','); const chartLegend=chartTop.map(([name,count],i)=>`<div class="pie-legend-row"><i style="background:${palette[i%palette.length]}"></i><span>${esc(name)}</span><b>${count} · ${(count/chartTotal*100).toFixed(1)}%</b></div>`).join('');
  document.querySelector('.stats-wrap').insertAdjacentHTML('beforeend',`<section class="pie-panel"><div class="pie-heading"><div><h2>สัดส่วนข้อมูลแบบ Pie Chart</h2><p>เลือกมุมมองที่ต้องการเปรียบเทียบ</p></div><select id="chart-mode"><option value="institution" ${chartMode==='institution'?'selected':''}>ตามมหาวิทยาลัย / สถาบัน</option><option value="faculty" ${chartMode==='faculty'?'selected':''}>ตามคณะ</option></select></div><div class="pie-layout"><div class="pie-chart" style="background:conic-gradient(${stops})"><span>${chartTotal}<small>รายการ</small></span></div><div class="pie-legend">${chartLegend||'<p>ยังไม่มีข้อมูล</p>'}</div></div></section><section class="insight-grid"><div class="insight-panel"><h2>ภาพรวมตามประเภทสถาบัน</h2><p>ช่วยดูว่ารุ่นพี่กระจายอยู่ในสถาบันประเภทใด</p><div class="insight-types">${typeCards}</div></div><div class="insight-panel"><h2>แนวโน้มจำนวนผู้ติดรายปี</h2><p>เปรียบเทียบจำนวนรูปในแต่ละปี</p><div class="trend-list">${trend}</div></div></section>`);
  document.querySelector('#stats-year').onchange=e=>{selected=e.target.value;render()};
  document.querySelector('#chart-mode').onchange=e=>{chartMode=e.target.value;render()};
  renderInteractivePie(chartTop,chartTotal,palette);
  const hero=document.querySelector('.hero-inner');if(hero){hero.querySelector('h1').textContent='สถิติการศึกษาต่อ';hero.querySelector('p').textContent='เลือกดูข้อมูลแยกตามปี หรือรวมข้อมูลทุกปี'}
  const heading=document.querySelector('.ranking-title h2');if(heading)heading.textContent=selected==='all'?'รวมทุกปี: มหาวิทยาลัย/สถาบัน':`ปี ${selected}: มหาวิทยาลัย/สถาบัน`;
  const rankingNote=document.querySelector('.ranking-title p');if(rankingNote)rankingNote.textContent='จำนวนและสัดส่วนของรายการที่รวบรวมได้ในช่วงที่เลือก';
  const pieTitle=document.querySelector('.pie-heading h2');if(pieTitle)pieTitle.textContent='สัดส่วนข้อมูล';
  const typeNote=document.querySelector('.insight-panel p');if(typeNote)typeNote.textContent='จำแนกข้อมูลตามประเภทของสถาบัน';
  const trendTitle=[...document.querySelectorAll('.insight-panel h2')].find(x=>x.textContent.includes('แนวโน้ม'));if(trendTitle){trendTitle.textContent='แนวโน้มจำนวนรายการรายปี';trendTitle.nextElementSibling.textContent='เปรียบเทียบจำนวนข้อมูลที่รวบรวมได้ในแต่ละปี'}
}
let statsFacebookLogo='';fetch('./site_settings.json').then(r=>r.ok?r.json():{}).then(settings=>{statsFacebookLogo=settings.facebookLogo||'';document.querySelector('.data-sources')?.remove();statsSourceObserver();}).catch(()=>{});
const statsSourceObserver=()=>{const hero=document.querySelector('.hero-inner');if(hero&&!hero.querySelector('.data-sources'))hero.insertAdjacentHTML('beforeend','<div class="data-sources"><strong>แหล่งที่มาของข้อมูล</strong><a href="https://www.facebook.com/bkwschoolpr" target="_blank" rel="noreferrer">'+(statsFacebookLogo?'<img class="social-icon social-image" src="'+esc(statsFacebookLogo)+'" alt="" aria-hidden="true">':'')+'เพจโรงเรียนบ้านเขว้าวิทยายน</a><a href="https://www.facebook.com/SaparBKWSchool" target="_blank" rel="noreferrer">'+(statsFacebookLogo?'<img class="social-icon social-image" src="'+esc(statsFacebookLogo)+'" alt="" aria-hidden="true">':'')+'เพจงานแนะแนวและประชาสัมพันธ์</a></div>')};const statsSourceMutationObserver=new MutationObserver(statsSourceObserver);statsSourceMutationObserver.observe(document.querySelector('#app'),{childList:true,subtree:true});
